[package]
name = "project_euler"
version = "0.0.1"
authors = ["Jake Marsden <jakemarsdenjm@gmail.com>"]
repository = "https://github.com/jakemarsden/project-euler-rust"
readme = "README.md"
license = "mit"
publish = false
edition = "2018"
